### ISSUE TITLE
Not an issue with your software but a question

### ISSUE THREAD

**Issue by e2002e** [PDi-Communication-Systems-Inc/ghostcommander#3]
Hello. How do you remount system to rw ?
When I use ghost commander it says "busy" then in a few seconds it does succeed. But the partition is rw only for ghost commander...
I need to do it from the terminal so that I can copy some files for other apps but it just won't remount it, I can unmount it with option -l but then the mount program is in system so you see my issue...
I have no other way of knowing now than to ask here. Regards.

**Comment by jtsmith** [comment]
Ghost commander is not our software.  We simply forked it and I cannot offer any support.
But I can give you a tip to try.  Assuming you are root on the console then this may work for you.

mount -o rw,remount /system

**Comment by e2002e** [comment]
That is the command i'm issuing as root, and where the output is that the partition is busy.
I'm trying now to use the 'mount' panel of ghost commander which I overlooked before.
What puzzles me most is that the partition are clearly being remounted rw since I can copy my files in system with ghost commander, but others app that need to write there too will fail, and a terminal emulator will confirm that it is ro. I really wonder how they force the remount. I am fighting to get my nexus 7 with a bc4330 chipset to be able to use monitor mode with internal card on android 7 if you want to know... and [nexmon](https://github.com/seemoo-lab/nexmon) seems to be stuck because of the ro partitions. I'm sure I'm going to manage that ! 
Thanks for the answer.

**Comment by jtsmith** [comment]
Could SELinux be blocking you from writing?  Do you see “avc” errors on the command line or from logcat?

**Comment by e2002e** [comment]
I don't know much about Selinux but it's set to permissive and any other file operation is fine.
Nothing about avc neither on the command line nor in logcat, what is that ?
And guess what I find out after all my attempts ? The command works very fine when I put rw before remount...
su -c "mount -o rw,remount /system" OK
su -c "mount -o remount,rw /system" FAIL ressource busy
